package com.pfe.entities;
// Generated 24 mai 2020 16:44:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Commande generated by hbm2java
 */
@Entity
@Table(name = "commande", catalog = "form_db")
public class Commande implements java.io.Serializable {

	private String cinCmd;
	private Produit produit;
	private Integer numCmd;
	private Date dateCmd;
	private Set<Epicier> epiciers = new HashSet<Epicier>(0);

	public Commande() {
	}

	public Commande(String cinCmd) {
		this.cinCmd = cinCmd;
	}

	public Commande(String cinCmd, Produit produit, Integer numCmd, Date dateCmd, Set<Epicier> epiciers) {
		this.cinCmd = cinCmd;
		this.produit = produit;
		this.numCmd = numCmd;
		this.dateCmd = dateCmd;
		this.epiciers = epiciers;
	}

	@Id

	@Column(name = "cin_cmd", unique = true, nullable = false)
	public String getCinCmd() {
		return this.cinCmd;
	}

	public void setCinCmd(String cinCmd) {
		this.cinCmd = cinCmd;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "article")
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "num_cmd")
	public Integer getNumCmd() {
		return this.numCmd;
	}

	public void setNumCmd(Integer numCmd) {
		this.numCmd = numCmd;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_cmd", length = 10)
	public Date getDateCmd() {
		return this.dateCmd;
	}

	public void setDateCmd(Date dateCmd) {
		this.dateCmd = dateCmd;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "commande")
	public Set<Epicier> getEpiciers() {
		return this.epiciers;
	}

	public void setEpiciers(Set<Epicier> epiciers) {
		this.epiciers = epiciers;
	}

}
