package com.pfe.entities;
// Generated 24 mai 2020 16:44:20 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Fournisseur generated by hbm2java
 */
@Entity
@Table(name = "fournisseur", catalog = "form_db")
public class Fournisseur implements java.io.Serializable {

	private String cinFsr;
	private String nomFsr;
	private String prenomFsr;
	private String adresseFsr;
	private String nomEntreprise;
	private String mailFsr;
	private String numFsr;

	public Fournisseur() {
	}

	public Fournisseur(String cinFsr) {
		this.cinFsr = cinFsr;
	}

	public Fournisseur(String cinFsr, String nomFsr, String prenomFsr, String adresseFsr, String nomEntreprise,
			String mailFsr, String numFsr) {
		this.cinFsr = cinFsr;
		this.nomFsr = nomFsr;
		this.prenomFsr = prenomFsr;
		this.adresseFsr = adresseFsr;
		this.nomEntreprise = nomEntreprise;
		this.mailFsr = mailFsr;
		this.numFsr = numFsr;
	}

	@Id

	@Column(name = "cin_fsr", unique = true, nullable = false)
	public String getCinFsr() {
		return this.cinFsr;
	}

	public void setCinFsr(String cinFsr) {
		this.cinFsr = cinFsr;
	}

	@Column(name = "nom_fsr")
	public String getNomFsr() {
		return this.nomFsr;
	}

	public void setNomFsr(String nomFsr) {
		this.nomFsr = nomFsr;
	}

	@Column(name = "prenom_fsr")
	public String getPrenomFsr() {
		return this.prenomFsr;
	}

	public void setPrenomFsr(String prenomFsr) {
		this.prenomFsr = prenomFsr;
	}

	@Column(name = "adresse_fsr")
	public String getAdresseFsr() {
		return this.adresseFsr;
	}

	public void setAdresseFsr(String adresseFsr) {
		this.adresseFsr = adresseFsr;
	}

	@Column(name = "nom_entreprise")
	public String getNomEntreprise() {
		return this.nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	@Column(name = "mail_fsr")
	public String getMailFsr() {
		return this.mailFsr;
	}

	public void setMailFsr(String mailFsr) {
		this.mailFsr = mailFsr;
	}

	@Column(name = "num_fsr")
	public String getNumFsr() {
		return this.numFsr;
	}

	public void setNumFsr(String numFsr) {
		this.numFsr = numFsr;
	}

}
