package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Caisse generated by hbm2java
 */
@Entity
@Table(name = "caisse", catalog = "basi_hanouta")
public class Caisse implements java.io.Serializable {

	private String cinCaisse;
	private Produit produit;
	private Double entréeEnDinars;
	private Double sortieEnDinars;
	private Date date;
	private Double gain;
	private Double totalEntées;
	private Double totalSortie;
	private Double gainTotal;

	public Caisse() {
		produit=new Produit();
	}

	public Caisse(String cinCaisse) {
		this.cinCaisse = cinCaisse;
	}

	public Caisse(String cinCaisse, Produit produit, Double entréeEnDinars, Double sortieEnDinars, Date date,
			Double gain, Double totalEntées, Double totalSortie, Double gainTotal) {
		this.cinCaisse = cinCaisse;
		this.produit = produit;
		this.entréeEnDinars = entréeEnDinars;
		this.sortieEnDinars = sortieEnDinars;
		this.date = date;
		this.gain = gain;
		this.totalEntées = totalEntées;
		this.totalSortie = totalSortie;
		this.gainTotal = gainTotal;
	}

	@Id

	@Column(name = "cin_caisse", unique = true, nullable = false)
	public String getCinCaisse() {
		return this.cinCaisse;
	}

	public void setCinCaisse(String cinCaisse) {
		this.cinCaisse = cinCaisse;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "article")
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "entree_en_dinars", precision = 22, scale = 0)
	public Double getEntréeEnDinars() {
		return this.entréeEnDinars;
	}

	public void setEntréeEnDinars(Double entréeEnDinars) {
		this.entréeEnDinars = entréeEnDinars;
	}

	@Column(name = "sortie_en_dinars", precision = 22, scale = 0)
	public Double getSortieEnDinars() {
		return this.sortieEnDinars;
	}

	public void setSortieEnDinars(Double sortieEnDinars) {
		this.sortieEnDinars = sortieEnDinars;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "gain", precision = 22, scale = 0)
	public Double getGain() {
		return this.gain;
	}

	public void setGain(Double gain) {
		this.gain = gain;
	}

	@Column(name = "total_entees", precision = 22, scale = 0)
	public Double getTotalEntées() {
		return this.totalEntées;
	}

	public void setTotalEntées(Double totalEntées) {
		this.totalEntées = totalEntées;
	}

	@Column(name = "total_sortie", precision = 22, scale = 0)
	public Double getTotalSortie() {
		return this.totalSortie;
	}

	public void setTotalSortie(Double totalSortie) {
		this.totalSortie = totalSortie;
	}

	@Column(name = "gain_total", precision = 22, scale = 0)
	public Double getGainTotal() {
		return this.gainTotal;
	}

	public void setGainTotal(Double gainTotal) {
		this.gainTotal = gainTotal;
	}

}
