package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", catalog = "basi_hanouta")
public class Client implements java.io.Serializable {

	private int cinClt;
	private Produit produit;
	private String nomClt;
	private String prenomClt;
	private String adresseClt;
	private String villeClt;
	private String mailClt;
	private double totalCredits;
	private Date date;

	public Client() {
		produit=new Produit();
	}

	public Client(int cinClt, double totalCredits, Date date) {
		this.cinClt = cinClt;
		this.totalCredits = totalCredits;
		this.date = date;
	}

	public Client(int cinClt, Produit produit, String nomClt, String prenomClt, String adresseClt, String villeClt,
			String mailClt, double totalCredits, Date date) {
		this.cinClt = cinClt;
		this.produit = produit;
		this.nomClt = nomClt;
		this.prenomClt = prenomClt;
		this.adresseClt = adresseClt;
		this.villeClt = villeClt;
		this.mailClt = mailClt;
		this.totalCredits = totalCredits;
		this.date = date;
	}

	@Id

	@Column(name = "cin_clt", unique = true, nullable = false)
	public int getCinClt() {
		return this.cinClt;
	}

	public void setCinClt(int cinClt) {
		this.cinClt = cinClt;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "article")
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "nom_clt")
	public String getNomClt() {
		return this.nomClt;
	}

	public void setNomClt(String nomClt) {
		this.nomClt = nomClt;
	}

	@Column(name = "prenom_clt")
	public String getPrenomClt() {
		return this.prenomClt;
	}

	public void setPrenomClt(String prenomClt) {
		this.prenomClt = prenomClt;
	}

	@Column(name = "adresse_clt")
	public String getAdresseClt() {
		return this.adresseClt;
	}

	public void setAdresseClt(String adresseClt) {
		this.adresseClt = adresseClt;
	}

	@Column(name = "ville_clt")
	public String getVilleClt() {
		return this.villeClt;
	}

	public void setVilleClt(String villeClt) {
		this.villeClt = villeClt;
	}

	@Column(name = "mail_clt")
	public String getMailClt() {
		return this.mailClt;
	}

	public void setMailClt(String mailClt) {
		this.mailClt = mailClt;
	}

	@Column(name = "totalCredits", nullable = false, precision = 22, scale = 0)
	public double getTotalCredits() {
		return this.totalCredits;
	}

	public void setTotalCredits(double totalCredits) {
		this.totalCredits = totalCredits;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", nullable = false, length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

}
