package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Epicier generated by hbm2java
 */
@Entity
@Table(name = "epicier", catalog = "basi_hanouta")
public class Epicier implements java.io.Serializable {

	private String cinEpicier;
	private Commande commande;
	private String nomEpicier;
	private String prenomEpicier;
	private String adresseEpicier;
	private String mailEpicier;
	private String villeEpicier;

	public Epicier() {
		commande = new Commande();
	}

	public Epicier(String cinEpicier) {
		this.cinEpicier = cinEpicier;
	}

	public Epicier(String cinEpicier, Commande commande, String nomEpicier, String prenomEpicier, String adresseEpicier,
			String mailEpicier, String villeEpicier) {
		this.cinEpicier = cinEpicier;
		this.commande = commande;
		this.nomEpicier = nomEpicier;
		this.prenomEpicier = prenomEpicier;
		this.adresseEpicier = adresseEpicier;
		this.mailEpicier = mailEpicier;
		this.villeEpicier = villeEpicier;
	}

	@Id

	@Column(name = "cin_epicier", unique = true, nullable = false)
	public String getCinEpicier() {
		return this.cinEpicier;
	}

	public void setCinEpicier(String cinEpicier) {
		this.cinEpicier = cinEpicier;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "cin_cmd")
	public Commande getCommande() {
		return this.commande;
	}

	public void setCommande(Commande commande) {
		this.commande = commande;
	}

	@Column(name = "nom_epicier")
	public String getNomEpicier() {
		return this.nomEpicier;
	}

	public void setNomEpicier(String nomEpicier) {
		this.nomEpicier = nomEpicier;
	}

	@Column(name = "prenom_epicier")
	public String getPrenomEpicier() {
		return this.prenomEpicier;
	}

	public void setPrenomEpicier(String prenomEpicier) {
		this.prenomEpicier = prenomEpicier;
	}

	@Column(name = "adresse_epicier")
	public String getAdresseEpicier() {
		return this.adresseEpicier;
	}

	public void setAdresseEpicier(String adresseEpicier) {
		this.adresseEpicier = adresseEpicier;
	}

	@Column(name = "mail_epicier")
	public String getMailEpicier() {
		return this.mailEpicier;
	}

	public void setMailEpicier(String mailEpicier) {
		this.mailEpicier = mailEpicier;
	}

	@Column(name = "ville_epicier")
	public String getVilleEpicier() {
		return this.villeEpicier;
	}

	public void setVilleEpicier(String villeEpicier) {
		this.villeEpicier = villeEpicier;
	}

}
