package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Facture generated by hbm2java
 */
@Entity
@Table(name = "facture", catalog = "basi_hanouta")
public class Facture implements java.io.Serializable {

	private String code;
	private Produit produit;
	private Integer quantité;
	private Double prixUnitaire;
	private Double prixTotal;
	private Double total;
	private String nomEntreprise;
	private String adresseEntreprise;
	private Integer numEntreprise;
	private Date date;
	private Double recu;
	private Double rendu;
	private Double reste;
	private String cas;

	public Facture() {
	}

	public Facture(String code) {
		this.code = code;
	}

	public Facture(String code, Produit produit, Integer quantité, Double prixUnitaire, Double prixTotal, Double total,
			String nomEntreprise, String adresseEntreprise, Integer numEntreprise, Date date, Double recu, Double rendu,
			Double reste, String cas) {
		this.code = code;
		this.produit = produit;
		this.quantité = quantité;
		this.prixUnitaire = prixUnitaire;
		this.prixTotal = prixTotal;
		this.total = total;
		this.nomEntreprise = nomEntreprise;
		this.adresseEntreprise = adresseEntreprise;
		this.numEntreprise = numEntreprise;
		this.date = date;
		this.recu = recu;
		this.rendu = rendu;
		this.reste = reste;
		this.cas = cas;
	}

	@Id

	@Column(name = "code", unique = true, nullable = false)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "article")
	public Produit getProduit() {
		return this.produit;
	}

	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "quantite")
	public Integer getQuantité() {
		return this.quantité;
	}

	public void setQuantité(Integer quantité) {
		this.quantité = quantité;
	}

	@Column(name = "prix_unitaire", precision = 22, scale = 0)
	public Double getPrixUnitaire() {
		return this.prixUnitaire;
	}

	public void setPrixUnitaire(Double prixUnitaire) {
		this.prixUnitaire = prixUnitaire;
	}

	@Column(name = "prix_total", precision = 22, scale = 0)
	public Double getPrixTotal() {
		return this.prixTotal;
	}

	public void setPrixTotal(Double prixTotal) {
		this.prixTotal = prixTotal;
	}

	@Column(name = "total", precision = 22, scale = 0)
	public Double getTotal() {
		return this.total;
	}

	public void setTotal(Double total) {
		this.total = total;
	}

	@Column(name = "nom_entreprise")
	public String getNomEntreprise() {
		return this.nomEntreprise;
	}

	public void setNomEntreprise(String nomEntreprise) {
		this.nomEntreprise = nomEntreprise;
	}

	@Column(name = "adresse_entreprise")
	public String getAdresseEntreprise() {
		return this.adresseEntreprise;
	}

	public void setAdresseEntreprise(String adresseEntreprise) {
		this.adresseEntreprise = adresseEntreprise;
	}

	@Column(name = "num_entreprise")
	public Integer getNumEntreprise() {
		return this.numEntreprise;
	}

	public void setNumEntreprise(Integer numEntreprise) {
		this.numEntreprise = numEntreprise;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "recu", precision = 22, scale = 0)
	public Double getRecu() {
		return this.recu;
	}

	public void setRecu(Double recu) {
		this.recu = recu;
	}

	@Column(name = "rendu", precision = 22, scale = 0)
	public Double getRendu() {
		return this.rendu;
	}

	public void setRendu(Double rendu) {
		this.rendu = rendu;
	}

	@Column(name = "reste", precision = 22, scale = 0)
	public Double getReste() {
		return this.reste;
	}

	public void setReste(Double reste) {
		this.reste = reste;
	}

	@Column(name = "cas")
	public String getCas() {
		return this.cas;
	}

	public void setCas(String cas) {
		this.cas = cas;
	}

}
