package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Produit generated by hbm2java
 */
@Entity
@Table(name = "produit", catalog = "basi_hanouta")
public class Produit implements java.io.Serializable {

	private String article;
	private Double prixAcheté;
	private Double prixVendue;
	private Set<Client> clients = new HashSet<Client>(0);
	private Set<Stock> stocks = new HashSet<Stock>(0);
	private Set<Caisse> caisses = new HashSet<Caisse>(0);
	private Set<Facture> factures = new HashSet<Facture>(0);
	private Set<Commande> commandes = new HashSet<Commande>(0);

	public Produit() {
	}

	public Produit(String article) {
		this.article = article;
	}

	public Produit(String article, Double prixAcheté, Double prixVendue, Set<Client> clients, Set<Stock> stocks,
			Set<Caisse> caisses, Set<Facture> factures, Set<Commande> commandes) {
		this.article = article;
		this.prixAcheté = prixAcheté;
		this.prixVendue = prixVendue;
		this.clients = clients;
		this.stocks = stocks;
		this.caisses = caisses;
		this.factures = factures;
		this.commandes = commandes;
	}

	@Id

	@Column(name = "article", unique = true, nullable = false)
	public String getArticle() {
		return this.article;
	}

	public void setArticle(String article) {
		this.article = article;
	}

	@Column(name = "prixAchete", precision = 22, scale = 0)
	public Double getprixAcheté() {
		return this.prixAcheté;
	}

	public void setprixAcheté(Double prixAcheté) {
		this.prixAcheté = prixAcheté;
	}

	@Column(name = "prixVendue", precision = 22, scale = 0)
	public Double getPrixVendue() {
		return this.prixVendue;
	}

	public void setPrixVendue(Double prixVendue) {
		this.prixVendue = prixVendue;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Stock> getStocks() {
		return this.stocks;
	}

	public void setStocks(Set<Stock> stocks) {
		this.stocks = stocks;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Caisse> getCaisses() {
		return this.caisses;
	}

	public void setCaisses(Set<Caisse> caisses) {
		this.caisses = caisses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Facture> getFactures() {
		return this.factures;
	}

	public void setFactures(Set<Facture> factures) {
		this.factures = factures;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "produit")
	public Set<Commande> getCommandes() {
		return this.commandes;
	}

	public void setCommandes(Set<Commande> commandes) {
		this.commandes = commandes;
	}

}
