package com.entities;
// Generated 30 mai 2020 01:39:20 by Hibernate Tools 4.3.5.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Stock generated by hbm2java
 */
@Entity
@Table(name = "stock", catalog = "basi_hanouta")
public class Stock implements java.io.Serializable {

	private String libellé;
	private Produit produit;
	private String entrée;
	private String sortie;
	private String stockInitial;
	private String stockFinal;
	private String existant;
	private Date date;
	private Integer quantitéE;
	private Double PUE;
	private Double montantE;
	private Integer quantitéS;
	private Double PUS;
	private Double montantS;
	private Integer quantitéStk;
	private Double PUStk;
	private Double montantStk;
	private String méthode;
	private String existance;
	private String mouvement;

	public Stock() {
		
		
		produit=new Produit();
		
	}

	public Stock(String libellé) {
		this.libellé = libellé;
	}

	public Stock(String libellé, Produit produit, String entrée, String sortie, String stockInitial, String stockFinal,
			String existant, Date date, Integer quantitéE, Double PUE, Double montantE, Integer quantitéS, Double PUS,
			Double montantS, Integer quantitéStk, Double PUStk, Double montantStk, String méthode, String existance,
			String mouvement) {
		this.libellé = libellé;
		this.produit = produit;
		this.entrée = entrée;
		this.sortie = sortie;
		this.stockInitial = stockInitial;
		this.stockFinal = stockFinal;
		this.existant = existant;
		this.date = date;
		this.quantitéE = quantitéE;
		this.PUE = PUE;
		this.montantE = montantE;
		this.quantitéS = quantitéS;
		this.PUS = PUS;
		this.montantS = montantS;
		this.quantitéStk = quantitéStk;
		this.PUStk = PUStk;
		this.montantStk = montantStk;
		this.méthode = méthode;
		this.existance = existance;
		this.mouvement = mouvement;
	}

	@Id

	@Column(name = "libelle", unique = true, nullable = false)
	public String getLibellé() {
		return this.libellé;
	}

	public void setLibellé(String libellé) {
		this.libellé = libellé;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "article")
	public Produit getProduit() {
		return this.produit;
	}
	
	


	public void setProduit(Produit produit) {
		this.produit = produit;
	}

	@Column(name = "entree")
	public String getEntrée() {
		return this.entrée;
	}

	public void setEntrée(String entrée) {
		this.entrée = entrée;
	}

	@Column(name = "sortie")
	public String getSortie() {
		return this.sortie;
	}

	public void setSortie(String sortie) {
		this.sortie = sortie;
	}

	@Column(name = "stock_initial")
	public String getStockInitial() {
		return this.stockInitial;
	}

	public void setStockInitial(String stockInitial) {
		this.stockInitial = stockInitial;
	}

	@Column(name = "stock_final")
	public String getStockFinal() {
		return this.stockFinal;
	}

	public void setStockFinal(String stockFinal) {
		this.stockFinal = stockFinal;
	}

	@Column(name = "existant")
	public String getExistant() {
		return this.existant;
	}

	public void setExistant(String existant) {
		this.existant = existant;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "quantite_e")
	public Integer getQuantitéE() {
		return this.quantitéE;
	}

	public void setQuantitéE(Integer quantitéE) {
		this.quantitéE = quantitéE;
	}

	@Column(name = "p_u_e", precision = 22, scale = 0)
	public Double getPUE() {
		return this.PUE;
	}

	public void setPUE(Double PUE) {
		this.PUE = PUE;
	}

	@Column(name = "montant_e", precision = 22, scale = 0)
	public Double getMontantE() {
		return this.montantE;
	}

	public void setMontantE(Double montantE) {
		this.montantE = montantE;
	}

	@Column(name = "quantite_s")
	public Integer getQuantitéS() {
		return this.quantitéS;
	}

	public void setQuantitéS(Integer quantitéS) {
		this.quantitéS = quantitéS;
	}

	@Column(name = "p_u_s", precision = 22, scale = 0)
	public Double getPUS() {
		return this.PUS;
	}

	public void setPUS(Double PUS) {
		this.PUS = PUS;
	}

	@Column(name = "montant_s", precision = 22, scale = 0)
	public Double getMontantS() {
		return this.montantS;
	}

	public void setMontantS(Double montantS) {
		this.montantS = montantS;
	}

	@Column(name = "quantite_stk")
	public Integer getQuantitéStk() {
		return this.quantitéStk;
	}

	public void setQuantitéStk(Integer quantitéStk) {
		this.quantitéStk = quantitéStk;
	}

	@Column(name = "p_u_stk", precision = 22, scale = 0)
	public Double getPUStk() {
		return this.PUStk;
	}

	public void setPUStk(Double PUStk) {
		this.PUStk = PUStk;
	}

	@Column(name = "montant_stk", precision = 22, scale = 0)
	public Double getMontantStk() {
		return this.montantStk;
	}

	public void setMontantStk(Double montantStk) {
		this.montantStk = montantStk;
	}

	@Column(name = "methode")
	public String getMéthode() {
		return this.méthode;
	}

	public void setMéthode(String méthode) {
		this.méthode = méthode;
	}

	@Column(name = "existance")
	public String getExistance() {
		return this.existance;
	}

	public void setExistance(String existance) {
		this.existance = existance;
	}

	@Column(name = "mouvement")
	public String getMouvement() {
		return this.mouvement;
	}

	public void setMouvement(String mouvement) {
		this.mouvement = mouvement;
	}
	
	

}
